#!/usr/bin/env python3
"""Step 4b: build a compact HTML page for selected high-quality examples.

Input:
  --rubrics JSONL from step2/filtered query-rubric records.
  --eval-xlsx XLSX evaluation dataset generated by step3.
  --result-csv rollout/evaluation result CSV.
  --case-ids comma-separated case ids to include.

Output:
  HTML page with selected examples, score distribution, positive/negative
  boundaries, retrieval hits, and answer hits.
"""

from __future__ import annotations

import argparse
import csv
import html
import json
import re
import sys
import zipfile
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict, List

from pipeline_utils import as_list, iter_jsonl, load_json_maybe, raise_csv_field_limit

SCRIPT_DIR = Path(__file__).resolve().parent
LEGACY_SCRIPTS = SCRIPT_DIR.parents[1] / "scripts"
if str(LEGACY_SCRIPTS) not in sys.path:
    sys.path.append(str(LEGACY_SCRIPTS))

from synthesize_query_joint import call_llm, get_api_key, resolve_provider_defaults  # noqa: E402


CASE_NOTES = {
    "train_line1": "材料作用域边界清楚：商家能力可重叠，因此问题被限定为“材料中美区自运营栏目归属”，能检验模型是否混入其他栏目。",
    "train_line10": "正负属性接近：公式/查找引用不可直接引用，数字/人员字段可作为间接方案，容易被模型把 workaround 误归入不可直接引用。",
    "train_line12": "同主题入口细分明确：抖音 App 内入口、抖音来客入口、PC 平台入口都相关，但归属不同，适合训练细分属性边界。",
    "train_line14": "召回策略同属推荐系统，但触发信号不同：用户行为触发 vs 内容热度触发，容易出现主题相关性误纳入。",
}

HIT_JUDGE_VERSION = "v4_rule_negative"

HIT_JUDGE_PROMPT = """你是 rollout 命中分析器，用于判断召回材料和最终答案是否命中 rubric 中的 positive/negative 边界。

判定对象：
- retrieval_text：召回材料。只要材料中出现或语义包含某个边界项，就算该材料命中。
- answer_text：答题模型最终答案。只有答案把边界项作为正确答案、并列答案、目标属性成员、满足目标条件的对象纳入时，才算答案命中。
- judge_reason：机评理由。仅作辅助定位；如果最终答案太长或表达为同义变体，而机评理由明确说“答案纳入/混入/作为正确答案”的某个 negative，也可据此判定 answer_negative 命中。

重要规则：
- negative 在否定、排除、对比语境中出现，不算 answer_negative 命中。
- 同义改写、斜杠枚举、简称、词序变化都要识别。例如“有供应链资源的工贸一体/工厂/贸易商”与“有供应链资源的工厂型、工贸一体型、贸易型商家”应视为命中同一 negative。
- 如果材料或 judge_reason 明确说明某类内容属于“可直接引用 / 可用于间接实现 / 其他模式 / 非目标类别”，而最终答案又把它作为目标答案纳入，算 answer_negative 命中。
- negative 不限于枚举实体。如果 negative_boundary 中包含“边界规则/判0规则”，而 answer_text 或 judge_reason 明确违反该规则，也要返回一个概括性的 answer_negative 命中项，例如“混入未标注性质建筑：10-5至10-9数据中心机房楼”“混入旧赛季皮肤奖励”“混入非目标对象权益”。
- 如果 judge_reason 明确说明因为某些额外混入项判0，即使这些混入项不在枚举 negative 列表里，也应把这些混入项作为 answer_negative_hits 返回。
- 不要把“未列入 positive_boundary 但材料明确说不可直接引用/属于目标类别”的内容算作 negative。比如问题问“不可直接引用的字段类型”，答案列出材料明确说不可直接引用的附件、图片、日期等字段，不应仅因不在公式/查找引用列表中就算命中 negative。
- 对审批引用多维表格控件这类 case，重点判断答案是否把可引用字段（尤其数字类型字段、人员类型字段，也包括文本、单选、多选、货币等支持直接引用字段）错误归入“不可直接引用”。如果这些字段仅出现在“支持直接引用”“对比参考”“间接实现到这些字段后再引用”等语境中，不算 answer_negative 命中。
- 不要因为词面相似就误判；必须语义上对应同一个边界项。

只输出严格 JSON：
{
  "retrieval_positive_hits": ["命中的 positive 边界项"],
  "retrieval_negative_hits": ["命中的 negative 边界项"],
  "answer_positive_hits": ["命中的 positive 边界项"],
  "answer_negative_hits": ["命中的 negative 边界项"],
  "reason": "一句话说明 negative 命中判断"
}
"""


def base_case_id(data_id: str) -> str:
    return str(data_id or "").split("__sample", 1)[0]


def compact_list(values: Any, limit: int = 12) -> List[str]:
    out = []
    seen = set()
    for value in as_list(values):
        text = str(value or "").strip()
        if not text or text in seen:
            continue
        seen.add(text)
        out.append(text)
        if len(out) >= limit:
            break
    return out


def collect_positive_terms(qp: Dict[str, Any]) -> List[str]:
    selected = qp.get("selected_contrast_set") or {}
    boundary = qp.get("answer_boundary") or {}
    rubric = qp.get("rubric") or {}
    terms = []
    terms += as_list(selected.get("positive_entities"))
    terms += as_list(boundary.get("required_attributes"))
    terms += as_list(boundary.get("allowed_entities"))
    if rubric.get("score_1"):
        terms.append("正例规则：" + str(rubric.get("score_1")))
    return compact_list(terms, limit=80)


def collect_negative_terms(qp: Dict[str, Any]) -> List[str]:
    selected = qp.get("selected_contrast_set") or {}
    boundary = qp.get("answer_boundary") or {}
    rubric = qp.get("rubric") or {}
    terms = []
    terms += as_list(selected.get("hard_negative_entities"))
    terms += as_list(selected.get("negative_attribute_values"))
    terms += as_list(boundary.get("must_exclude"))
    terms += as_list(rubric.get("zero_if_answer_asserts"))
    terms += as_list(rubric.get("zero_if_mentions"))
    terms += as_list(rubric.get("zero_if_contains"))
    if boundary.get("boundary_rule"):
        terms.append("边界规则：" + str(boundary.get("boundary_rule")))
    if rubric.get("score_0"):
        terms.append("判0规则：" + str(rubric.get("score_0")))
    return compact_list(terms, limit=80)


def query_plan(record: Dict[str, Any]) -> Dict[str, Any]:
    return (load_json_maybe(record.get("query_synthesis")).get("query_plan") or {})


def html_list(items: List[str]) -> str:
    if not items:
        return "<p class='muted'>无</p>"
    return "<ul>" + "".join(f"<li>{html.escape(x)}</li>" for x in items) + "</ul>"


def html_kv(rows: List[tuple[str, Any]]) -> str:
    return "<dl>" + "".join(
        f"<dt>{html.escape(k)}</dt><dd>{html.escape(str(v or ''))}</dd>" for k, v in rows
    ) + "</dl>"


def hit_badge_list(items: List[str], cls: str) -> str:
    if not items:
        return "<span class='empty'>未命中</span>"
    return "".join(f"<span class='hit {cls}'>{html.escape(x)}</span>" for x in items)


def pre(text: Any) -> str:
    return f"<pre>{html.escape(str(text or '').strip())}</pre>"


def category_labels(categories: Any) -> str:
    labels = compact_list([x.get("label") for x in as_list(categories) if isinstance(x, dict)], limit=80)
    return "；".join(labels)


def truncate(text: Any, limit: int = 1800) -> str:
    value = str(text or "").strip()
    if len(value) <= limit:
        return value
    return value[:limit] + "\n...[truncated]"


def clip(text: Any, limit: int) -> str:
    value = str(text or "").strip()
    if len(value) <= limit:
        return value
    half = limit // 2
    return value[:half] + "\n...[middle truncated]...\n" + value[-half:]


def load_hit_cache(path: Path) -> Dict[str, Dict[str, Any]]:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {}


def load_local_api_key(provider: str) -> str:
    config_path = SCRIPT_DIR / "llm_config.jsonl"
    if provider != "ark" or not config_path.exists():
        return ""
    text = config_path.read_text(encoding="utf-8")
    match = re.search(r"\bkey\s*:\s*([^\s]+)", text)
    return match.group(1).strip() if match else ""


def save_hit_cache(path: Path, cache: Dict[str, Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(cache, ensure_ascii=False, indent=2), encoding="utf-8")


def string_list(value: Any) -> List[str]:
    return [str(x) for x in as_list(value) if str(x or "").strip()]


def judge_rollout_hits(
    run: Dict[str, str],
    positive_terms: List[str],
    negative_terms: List[str],
    provider: str,
    model: str,
    api_key: str,
    endpoint: str,
    max_output_tokens: int,
    cache: Dict[str, Dict[str, Any]],
) -> Dict[str, Any]:
    cache_key = "|".join(
        [
            HIT_JUDGE_VERSION,
            run.get("dataID", ""),
            provider,
            model,
            str(len(run.get("output", ""))),
            str(len(retrieval_text(run))),
        ]
    )
    cached = cache.get(cache_key)
    if cached:
        return cached

    payload = {
        "dataID": run.get("dataID", ""),
        "query": run.get("query", ""),
        "positive_boundary": positive_terms,
        "negative_boundary": negative_terms,
        "retrieval_text": clip(retrieval_text(run), 9000),
        "answer_text": clip(run.get("output", ""), 9000),
        "judge_reason": clip(run.get("llm_reason", "") or run.get("llm_res", ""), 5000),
    }
    result = call_llm(
        [
            {"role": "system", "content": HIT_JUDGE_PROMPT},
            {"role": "user", "content": json.dumps(payload, ensure_ascii=False, indent=2)},
        ],
        provider=provider,
        model=model,
        api_key=api_key,
        endpoint=endpoint,
        max_output_tokens=max_output_tokens,
    )
    normalized = {
        "retrieval_positive_hits": string_list(result.get("retrieval_positive_hits")),
        "retrieval_negative_hits": string_list(result.get("retrieval_negative_hits")),
        "answer_positive_hits": string_list(result.get("answer_positive_hits")),
        "answer_negative_hits": string_list(result.get("answer_negative_hits")),
        "reason": str(result.get("reason", "")),
    }
    cache[cache_key] = normalized
    return normalized


def choose_rollouts(rows: List[Dict[str, str]], judgments: Dict[str, Dict[str, Any]]) -> List[Dict[str, str]]:
    material_only = None
    material_and_answer = None
    for run in rows:
        judgment = judgments.get(run.get("dataID", ""), {})
        retrieval_neg = bool(judgment.get("retrieval_negative_hits"))
        answer_neg = bool(judgment.get("answer_negative_hits"))
        if retrieval_neg and not answer_neg and material_only is None:
            material_only = run
        if retrieval_neg and answer_neg and material_and_answer is None:
            material_and_answer = run
        if material_only and material_and_answer:
            return [material_only, material_and_answer]
    return []


def load_eval_xlsx(path: Path) -> Dict[str, Dict[str, str]]:
    with zipfile.ZipFile(path) as zf:
        xml = zf.read("xl/worksheets/sheet1.xml").decode("utf-8")
    rows: Dict[int, Dict[int, str]] = defaultdict(dict)
    for col_ref, row_ref, text in re.findall(r'<c r="([A-Z]+)(\d+)"[^>]*><is><t>(.*?)</t></is></c>', xml, re.S):
        col = 0
        for ch in col_ref:
            col = col * 26 + ord(ch) - ord("A") + 1
        rows[int(row_ref)][col] = html.unescape(text)
    header = rows.get(1, {})
    fields = [header[idx] for idx in sorted(header)]
    out = {}
    for row_idx in sorted(k for k in rows if k != 1):
        row = {fields[idx - 1]: rows[row_idx].get(idx, "") for idx in range(1, len(fields) + 1)}
        out[row.get("dataID", "")] = row
    return out


def load_results(path: Path) -> Dict[str, List[Dict[str, str]]]:
    raise_csv_field_limit()
    grouped: Dict[str, List[Dict[str, str]]] = defaultdict(list)
    with path.open(encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            grouped[base_case_id(row.get("dataID", ""))].append(row)
    return grouped


def retrieval_text(row: Dict[str, str]) -> str:
    return "\n".join(
        [
            row.get("passage1", ""),
            row.get("passage2", ""),
            row.get("passage3", ""),
            row.get("agenticV0Info", ""),
        ]
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rubrics", type=Path, required=True)
    parser.add_argument("--eval-xlsx", type=Path, required=True)
    parser.add_argument("--result-csv", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--case-ids", default="train_line1,train_line10,train_line12,train_line14")
    parser.add_argument("--provider", choices=["ark", "modelhub"], default="ark")
    parser.add_argument("--model", default="ep-20260225140859-njzr9")
    parser.add_argument("--api-key", default="")
    parser.add_argument("--endpoint", default="https://aidp.bytedance.net/api/modelhub/online/responses")
    parser.add_argument("--max-output-tokens", type=int, default=1600)
    parser.add_argument("--hit-cache", type=Path, default=None)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    resolve_provider_defaults(args)
    try:
        api_key = get_api_key(args)
    except ValueError:
        api_key = load_local_api_key(args.provider)
        if not api_key:
            raise
    hit_cache_path = args.hit_cache or args.output.with_suffix(".hit_cache.json")
    hit_cache = load_hit_cache(hit_cache_path)
    case_ids = [x.strip() for x in args.case_ids.split(",") if x.strip()]
    rubrics = {str(obj.get("case_id")): obj for _, obj in iter_jsonl(args.rubrics)}
    eval_rows = load_eval_xlsx(args.eval_xlsx)
    results = load_results(args.result_csv)

    css = """
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;margin:0;background:#f5f6f8;color:#1f2328}
header{padding:28px 36px;background:#fff;border-bottom:1px solid #dfe3e8}
main{padding:24px 36px;max-width:1440px;margin:0 auto}
h1{font-size:24px;margin:0 0 8px} h2{font-size:20px;margin:0 0 10px} h3{font-size:16px;margin:0 0 10px} h4{font-size:13px;margin:0 0 8px;color:#475467}
.muted{color:#667085}.case{background:#fff;border:1px solid #dfe3e8;border-radius:8px;margin:20px 0;padding:18px}
.section{border-top:1px solid #e5e7eb;padding-top:14px;margin-top:14px}
.meta{display:flex;gap:10px;flex-wrap:wrap;margin:8px 0 14px}.tag{background:#eef2f6;border:1px solid #d7dde5;border-radius:999px;padding:4px 10px;font-size:12px}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px}.grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px}
.panel{border:1px solid #e5e7eb;border-radius:8px;padding:12px;background:#fcfcfd;min-width:0}.wide{grid-column:1/-1}
.rollout{border:1px solid #dfe3e8;border-radius:8px;margin:12px 0;padding:12px;background:#fff}.score2{border-left:5px solid #16a34a}.score0{border-left:5px solid #dc2626}
pre{white-space:pre-wrap;word-break:break-word;margin:0;font-size:12px;line-height:1.45;max-height:360px;overflow:auto}
ul{margin:0;padding-left:20px}li{margin:4px 0}
dl{display:grid;grid-template-columns:120px 1fr;gap:6px 10px;margin:0}dt{font-weight:600;color:#475467}dd{margin:0}
.hit{display:inline-block;border-radius:999px;padding:3px 8px;margin:2px;font-size:12px;border:1px solid}.pos{background:#ecfdf3;border-color:#abefc6;color:#067647}.neg{background:#fef3f2;border-color:#fecdca;color:#b42318}
.empty{color:#98a2b3;font-size:12px}.answer-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:10px}
@media(max-width:1000px){main{padding:16px}.grid2,.grid3,.answer-grid{grid-template-columns:1fr}.wide{grid-column:auto}dl{grid-template-columns:1fr}}
"""
    parts = [
        "<!doctype html><html><head><meta charset='utf-8'>",
        "<title>精选 Query/Rubric 示例</title>",
        f"<style>{css}</style></head><body>",
        "<header><h1>精选 Query/Rubric 示例</h1>",
        "<p class='muted'>从 7x4 测试结果中挑选边界清楚、能体现正负例区分能力的案例。</p></header><main>",
    ]
    for case_id in case_ids:
        record = rubrics.get(case_id)
        if not record:
            continue
        qp = query_plan(record)
        selected = qp.get("selected_contrast_set") or {}
        taxonomy = qp.get("taxonomy") or {}
        rows = results.get(case_id, [])
        score_counter = Counter(str(r.get("可信分", "")).strip() for r in rows)
        eval_row = next((v for k, v in eval_rows.items() if base_case_id(k) == case_id), {})

        positive_terms = collect_positive_terms(qp)
        negative_terms = collect_negative_terms(qp)
        judgments: Dict[str, Dict[str, Any]] = {}
        for idx, run in enumerate(rows, 1):
            judgments[run.get("dataID", "")] = judge_rollout_hits(
                run,
                positive_terms,
                negative_terms,
                provider=args.provider,
                model=args.model,
                api_key=api_key,
                endpoint=args.endpoint,
                max_output_tokens=args.max_output_tokens,
                cache=hit_cache,
            )
            save_hit_cache(hit_cache_path, hit_cache)
            judgment = judgments[run.get("dataID", "")]
            print(
                f"[step4b] case={case_id} rollout={idx}/{len(rows)} dataID={run.get('dataID', '')} "
                f"score={run.get('可信分', '')} retrieval_neg={len(judgment.get('retrieval_negative_hits') or [])} "
                f"answer_neg={len(judgment.get('answer_negative_hits') or [])}",
                flush=True,
            )

        selected_rows = choose_rollouts(rows, judgments)
        if not selected_rows:
            continue

        parts.append("<article class='case'>")
        parts.append(f"<h2>{html.escape(case_id)}｜{html.escape(str(qp.get('query','')))}</h2>")
        parts.append("<div class='meta'>")
        parts.append(f"<span class='tag'>类型：{html.escape(str(qp.get('query_type','')))}</span>")
        parts.append(f"<span class='tag'>互斥性：{html.escape(str(taxonomy.get('mutual_exclusivity','')))}</span>")
        parts.append(f"<span class='tag'>分数分布：{html.escape(dict(score_counter).__repr__())}</span>")
        parts.append("</div>")
        parts.append(f"<p>{html.escape(CASE_NOTES.get(case_id, '边界清楚，适合展示。'))}</p>")

        parts.append("<section class='section'><h3>1. 原始 Query / 重构 Query</h3><div class='grid2'>")
        parts.append("<section class='panel'><h4>原始 query</h4>" + pre(record.get("original_user_query", "")) + "</section>")
        parts.append("<section class='panel'><h4>重构 query</h4>" + pre(qp.get("query", "")) + "</section>")
        parts.append("</div></section>")

        parts.append("<section class='section'><h3>2. 材料分类与边界构造</h3>")
        parts.append("<div class='grid2'>")
        parts.append(
            "<section class='panel wide'><h4>一级分类 / 二级属性</h4>"
            + html_kv(
                [
                    ("一级分类", taxonomy.get("primary_topic", "")),
                    ("二级属性", taxonomy.get("secondary_axis", "")),
                    ("二级类别", category_labels(taxonomy.get("categories", []))),
                ]
            )
            + "</section>"
        )
        parts.append("<section class='panel'><h4>Positive 边界</h4>" + html_list(compact_list(selected.get("positive_entities"))) + "</section>")
        parts.append("<section class='panel'><h4>Negative 边界</h4>" + html_list(compact_list(selected.get("hard_negative_entities"))) + "</section>")
        parts.append("</div></section>")

        parts.append("<section class='section'><h3>3. 机评引导</h3>")
        parts.append("<section class='panel'>" + pre(truncate(eval_row.get("预期答复（机评文本）", ""), 3600)) + "</section></section>")

        parts.append("<section class='section'><h3>4. Rollout Case 命中分析</h3>")
        for run in selected_rows:
            score = str(run.get("可信分", "")).strip()
            score_cls = "score2" if score in {"2", "2.0"} else "score0" if score in {"0", "0.0"} else ""
            judgment = judgments.get(run.get("dataID", ""), {})
            retrieval_hits_pos = string_list(judgment.get("retrieval_positive_hits"))
            retrieval_hits_neg = string_list(judgment.get("retrieval_negative_hits"))
            answer_hits_pos = string_list(judgment.get("answer_positive_hits"))
            answer_hits_neg = string_list(judgment.get("answer_negative_hits"))
            parts.append(f"<section class='rollout {score_cls}'><h4>{html.escape(run.get('dataID',''))}｜可信分 {html.escape(score)}</h4>")
            parts.append("<div class='grid2'>")
            parts.append("<section class='panel'><h4>召回材料命中的 Positive</h4>" + hit_badge_list(retrieval_hits_pos, "pos") + "</section>")
            parts.append("<section class='panel'><h4>召回材料命中的 Negative</h4>" + hit_badge_list(retrieval_hits_neg, "neg") + "</section>")
            parts.append("<section class='panel'><h4>回答命中的 Positive</h4>" + hit_badge_list(answer_hits_pos, "pos") + "</section>")
            parts.append("<section class='panel'><h4>回答命中的 Negative</h4>" + hit_badge_list(answer_hits_neg, "neg") + "</section>")
            parts.append("</div>")
            parts.append("<div class='answer-grid'>")
            parts.append("<section class='panel'><h4>回答内容</h4>" + pre(truncate(run.get("output", ""), 2200)) + "</section>")
            parts.append("<section class='panel'><h4>机评理由</h4>" + pre(truncate(run.get("llm_reason", ""), 1600)) + "</section>")
            parts.append("<section class='panel wide'><h4>LLM 命中判断说明</h4>" + pre(judgment.get("reason", "")) + "</section>")
            parts.append("</div>")
            parts.append("</section>")
        parts.append("</section></article>")
    parts.append("</main></body></html>")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote={args.output}")


if __name__ == "__main__":
    main()
